import type {Metadata} from 'next';
import './globals.css';
import QueryProvider from './api/components/QueryProvider';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <QueryProvider>
          <Header />
          <main className="container py-8">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
